### ISSUE TITLE
Openwebui Bridge Tutorial (windows)

### ISSUE THREAD

**Issue by bukit-kronik** [SecretiveShell/MCP-Bridge#5] opened 2024-12-11 10:20 UTC

**Comment by SecretiveShell** [comment] 2024-12-11 10:27
can you please elaborate on what the issue is?

if you want to run the application on windows, currently the best way is to use docker-desktop + compose.yml

alternatively, set the environment variables in powershell, setup the virtual environment and run main.py.

The config difficulties on windows should be resolved after #5 is merged, as you can just use a json file like Claude desktop.

**Comment by SecretiveShell** [comment] 2024-12-11 12:22
> Oh and btw, thank you for developing this MCP bridge, very very important.

Thanks, I am glad that you like it.

> Yeah, docker is not preferred by windows devs, wsl take 3gb+ of ram, pip is preferred.
> 
> Just need a step by step setting up MCP bridge, server and openwebui non docker way.

I am not aware of any way to run open web ui on windows without WSL, though there is nothing stopping you running MCP-Bridge on windows. I would suggest that you setup a python environment

```powershell
python -m venv .venv
.vene/scripts/activate
pip install -r requirements.txt
python mcp_bridge/main.py
```

you will need to set the environment variables appropriately, or target the branch for pr #4 and use a json file.

**Comment by SecretiveShell** [comment] 2024-12-11 12:24
If you need an inference server on windows, I would suggest ollama. They have a stable openai compatible tool use API and is easy to run without docker. (I tested this with vLLM only so far, but that would require docker desktop)

**Comment by SecretiveShell** [comment] 2024-12-11 17:46
@bukit-kronik please review the readme for the manual installation. This should work for windows.

**Closed as completed** 2024-12-12 18:24 UTC

**Comment by SecretiveShell** [comment] 2024-12-12 19:29
glad this worked
